services:
  - type: web
    name: roa-app
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn config.wsgi:application"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: DATABASE_URL
        sync: false   # Lo cargás manualmente desde Supabase
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
      - key: RENDER_EXTERNAL_HOSTNAME
        fromService:
          type: web
          name: roa-app
          property: host
    autoDeploy: true
