# Generated by Django 5.2.11 on 2026-03-02 21:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('dir_cliente', models.CharField(blank=True, max_length=300, verbose_name='Dirección')),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='EquipoAA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_qr', models.CharField(blank=True, db_index=True, help_text='ID único en el código QR (opcional por ahora)', max_length=100, null=True, unique=True)),
                ('nombre', models.CharField(help_text='Ej: UCA 1, UMA 2, SPLIT 1', max_length=200)),
                ('ubicacion', models.CharField(blank=True, help_text='Ej: AZOTEA, CUARTO RETORNO', max_length=200)),
                ('tipo_equipo', models.CharField(choices=[('UCA', 'UCA — Unidad Condensadora'), ('UMA', 'UMA — Unidad Manejadora'), ('SPLIT', 'Split'), ('CASSETTE', 'Cassette'), ('PISO_TECHO', 'Piso Techo'), ('OTRO', 'Otro')], default='UCA', max_length=20)),
                ('num_circuitos', models.PositiveSmallIntegerField(default=1, help_text='Número de circuitos (1 o 2). Aplica a UCA para determinar circuitos A y B.')),
                ('marca', models.CharField(blank=True, max_length=100)),
                ('modelo', models.CharField(blank=True, max_length=100)),
                ('capacidad', models.CharField(blank=True, help_text='Ej: 25TR', max_length=50)),
                ('refrigerante', models.CharField(blank=True, help_text='R410A, R22, R32, R407C, etc.', max_length=20)),
                ('voltaje', models.CharField(blank=True, help_text='Ej: 220 V', max_length=50)),
                ('activo_fijo', models.CharField(blank=True, help_text='Número de activo fijo', max_length=50)),
                ('activo', models.BooleanField(default=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipos', to='inventory.cliente')),
            ],
            options={
                'verbose_name': 'Equipo de AA',
                'verbose_name_plural': 'Equipos de AA',
                'ordering': ['cliente', 'nombre'],
            },
        ),
    ]
