# Generated by Django 5.2.11 on 2026-03-03 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipoaa',
            name='fases',
            field=models.CharField(blank=True, help_text='Ej: 3 PH 60HZ', max_length=50),
        ),
        migrations.AddField(
            model_name='equipoaa',
            name='tipo_correa',
            field=models.CharField(blank=True, help_text='Ej: BX38', max_length=50),
        ),
    ]
