# Generated by Django 5.2.12 on 2026-06-03 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_cliente_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipoaa',
            name='tipo_equipo',
            field=models.CharField(choices=[('UCA', 'UCA — Unidad Condensadora'), ('UMA', 'UMA — Unidad Manejadora'), ('SPLIT', 'Split'), ('CASSETTE', 'Cassette'), ('PISO_TECHO', 'Piso Techo'), ('PAQUETE', 'Paquete'), ('CONDENSADORA_RACK', 'Condensadora Rack Refrigeración'), ('OTRO', 'Otro')], default='UCA', max_length=20),
        ),
    ]
