# Generated by Django 5.2.11 on 2026-02-22 02:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_rename_refigerante_rack_refigerante'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compresor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveSmallIntegerField(help_text='Ej: 1, 2, 3...')),
                ('temperatura', models.CharField(choices=[('media', 'Media Temperatura'), ('baja', 'Baja Temperatura')], max_length=10)),
                ('modelo', models.CharField(blank=True, max_length=100)),
                ('serie', models.CharField(blank=True, max_length=100, verbose_name='Número de serie')),
                ('rack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_compresores', to='inventory.rack')),
            ],
            options={
                'verbose_name': 'Detalle de compresor',
                'verbose_name_plural': 'Detalles de compresores',
                'ordering': ['rack', 'temperatura', 'numero'],
                'unique_together': {('rack', 'numero')},
            },
        ),
    ]
