# Generated by Django 5.2.11 on 2026-03-02 21:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipoIntervenido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_equipo', models.CharField(help_text='Ej: UCA 1, UMA 2', max_length=200)),
                ('ubicacion', models.CharField(blank=True, max_length=200)),
                ('tipo_equipo', models.CharField(blank=True, help_text='SPLIT, CASSETTE, PISO TECHO, etc.', max_length=20)),
                ('marca', models.CharField(blank=True, max_length=100)),
                ('modelo', models.CharField(blank=True, max_length=100)),
                ('capacidad', models.CharField(blank=True, max_length=50)),
                ('refrigerante', models.CharField(blank=True, max_length=20)),
                ('voltaje', models.CharField(blank=True, max_length=50)),
                ('corriente_l1', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('corriente_l2', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('corriente_l3', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('amperaje_l1', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('amperaje_l2', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('amperaje_l3', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('fases', models.CharField(blank=True, help_text='Ej: 3 PH 60HZ', max_length=50)),
                ('tipo_correa', models.CharField(blank=True, help_text='Ej: BX38', max_length=50)),
                ('activo_fijo', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'verbose_name': 'Equipo Intervenido',
                'verbose_name_plural': 'Equipos Intervenidos',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='MedicionSplit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp_sumin_antes', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Temp. Suministro Antes (°C)')),
                ('temp_sumin_despues', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Temp. Suministro Después (°C)')),
                ('temp_retorno_antes', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Temp. Retorno Antes (°C)')),
                ('temp_retorno_despues', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Temp. Retorno Después (°C)')),
                ('equipo_intervenido', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='medicion_split', to='operations.equipointervenido')),
            ],
            options={
                'verbose_name': 'Medición Split/UMA',
                'verbose_name_plural': 'Mediciones Split/UMA',
            },
        ),
        migrations.CreateModel(
            name='Observacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(blank=True)),
                ('equipo_intervenido', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='observacion', to='operations.equipointervenido')),
            ],
            options={
                'verbose_name': 'Observación',
                'verbose_name_plural': 'Observaciones',
            },
        ),
        migrations.CreateModel(
            name='OrdenServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('MP', 'Mantenimiento Preventivo Tipo A'), ('MC', 'Mantenimiento Correctivo')], max_length=2, verbose_name='Tipo de mantenimiento')),
                ('radicado', models.CharField(help_text='Ej: MP9167 o MC1234', max_length=20, verbose_name='Radicado No.')),
                ('cliente_nombre', models.CharField(max_length=200, verbose_name='Cliente')),
                ('dir_cliente', models.CharField(blank=True, max_length=300, verbose_name='Dir. Cliente')),
                ('num_orden', models.CharField(blank=True, max_length=50, verbose_name='No. Orden de Servicio')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('mes', models.CharField(blank=True, max_length=20, verbose_name='Mes')),
                ('hora_inicio', models.DateTimeField()),
                ('hora_fin', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('abierto', 'Abierto'), ('cerrado', 'Cerrado')], default='abierto', max_length=10)),
                ('pdf_path', models.CharField(blank=True, max_length=500)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordenes', to='inventory.equipoaa')),
                ('tecnico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_servicio', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Orden de Servicio',
                'verbose_name_plural': 'Órdenes de Servicio',
                'ordering': ['-hora_inicio'],
            },
        ),
        migrations.AddField(
            model_name='equipointervenido',
            name='orden',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipos_intervenidos', to='operations.ordenservicio'),
        ),
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=500)),
                ('marcada', models.BooleanField(default=True)),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to='operations.ordenservicio')),
            ],
            options={
                'verbose_name': 'Actividad',
                'verbose_name_plural': 'Actividades',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='MedicionUCA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('circuito', models.CharField(choices=[('A', 'Circuito A'), ('B', 'Circuito B')], max_length=1)),
                ('baja_p_antes', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Baja presión Antes (PSI)')),
                ('baja_p_despues', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Baja presión Después (PSI)')),
                ('alta_p_antes', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Alta presión Antes (PSI)')),
                ('alta_p_despues', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Alta presión Después (PSI)')),
                ('equipo_intervenido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mediciones_uca', to='operations.equipointervenido')),
            ],
            options={
                'verbose_name': 'Medición UCA',
                'verbose_name_plural': 'Mediciones UCA',
                'unique_together': {('equipo_intervenido', 'circuito')},
            },
        ),
    ]
