# Generated by Django 5.2.11 on 2026-03-03 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordenservicio',
            name='tipo',
            field=models.CharField(choices=[('MP', 'Mantenimiento Preventivo MP'), ('MC', 'Mantenimiento Correctivo')], max_length=2, verbose_name='Tipo de mantenimiento'),
        ),
    ]
