# Generated by Django 5.2.11 on 2026-03-03 18:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('operations', '0002_alter_ordenservicio_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenservicio',
            name='cliente',
            field=models.ForeignKey(blank=True, help_text='Obligatorio para MP global. Nulo para MC por equipo.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_servicio', to='inventory.cliente'),
        ),
        migrations.AlterField(
            model_name='ordenservicio',
            name='equipo',
            field=models.ForeignKey(blank=True, help_text='Obligatorio para MC. Nulo para MP global por Tienda.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ordenes', to='inventory.equipoaa'),
        ),
    ]
