# Generated by Django 5.2.11 on 2026-03-07 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0003_ordenservicio_cliente_alter_ordenservicio_equipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordenservicio',
            name='num_orden',
        ),
    ]
