# Generated by Django 5.2.11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0004_remove_ordenservicio_num_orden'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicionCondensadoraRack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('corriente_l1_antes', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Corriente L1 Antes (A)')),
                ('corriente_l2_antes', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Corriente L2 Antes (A)')),
                ('corriente_l3_antes', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Corriente L3 Antes (A)')),
                ('presion_entrada_antes', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Presión de entrada a la condensadora Antes (PSI)')),
                ('temp_salida_antes', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Temperatura de salida abanicos Antes (°C)')),
                ('corriente_l1_despues', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Corriente L1 Después (A)')),
                ('corriente_l2_despues', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Corriente L2 Después (A)')),
                ('corriente_l3_despues', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Corriente L3 Después (A)')),
                ('presion_entrada_despues', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Presión de entrada a la condensadora Después (PSI)')),
                ('temp_salida_despues', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Temperatura de salida abanicos Después (°C)')),
                ('temp_ambiente_despues', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Temperatura ambiente Después (°C)')),
                ('total_abanicos', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Total abanicos')),
                ('abanicos_operativos', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Abanicos operativos')),
                ('equipo_intervenido', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='medicion_condensadora_rack', to='operations.equipointervenido')),
            ],
            options={
                'verbose_name': 'Medición Condensadora Rack',
                'verbose_name_plural': 'Mediciones Condensadora Rack',
            },
        ),
    ]
