# Generated by Django 5.2.12 on 2026-06-21 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0006_add_condensadora_rack_to_clientes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordenservicio',
            name='radicado',
            field=models.CharField(help_text='Ej: MP9167 o MC1234', max_length=20, unique=True, verbose_name='Radicado No.'),
        ),
    ]
